### ISSUE TITLE
Guide of use

### ISSUE THREAD

**Issue by a7med-95** [OPHoperHPO/image-background-remove-tool#1]
Can you provide a guide on how to run this on windows, for users with basic knowledge?
Which TensorFlow version is needed, etc ...

**Comment by a7med-95** [comment]
![image](https://user-images.githubusercontent.com/16699574/77229901-c43cc100-6b90-11ea-9f02-b8880d3cf2a6.png)

I am getting this error when running the script using the default images in Input folder

**Comment by OPHoperHPO** [comment]
In the next few days, I will post a new release of this tool, along with a guide for use in windows and versions of all dependencies in requirements.txt.

**Comment by OPHoperHPO** [comment]
Recheck your problem. I released a new release, so there should no longer be a problem.

**Comment by a7med-95** [comment]
Windows code works fine, Linux code has a syntax error on line 118 in main.py

![image](https://user-images.githubusercontent.com/16699574/77253360-e51d1900-6c59-11ea-921d-a2e8be71448f.png)

Also the requirements file in Linux gives error for tensorflow 2.1.0  (Not in windows)

**Comment by OPHoperHPO** [comment]
On which version of python do you run the program on Linux?

**Comment by OPHoperHPO** [comment]
I managed to reproduce your problem only on python 2.x.  The program **works only on python 3.x**, but not on python 2.x.
