### ISSUE TITLE
Doesn't work with 3090ti

### ISSUE THREAD

**Issue by 4omp** [OPHoperHPO/image-background-remove-tool#112]
Tried to run on a local PC with anaconda and CLI --cuda, but seems no GPU utilization. PyTorch recognize card and it works in others scripts.

**Comment by OPHoperHPO** [comment]
Hello @4omp. The `--cuda` argument is not in the list of available console interface arguments. As you can see in our README.md and in the CLI help message, the `--device cuda` flag can be used to start processing in cuda mode.
