### ISSUE TITLE
Need your help:Urgent

### ISSUE THREAD

**Issue by minakshimathpal** [OPHoperHPO/image-background-remove-tool#113]
@OPHoperHPO Hi there. Thank You for this wonderful work
I have few images for which I am not getting smooth results. Here are the results
![image](https://user-images.githubusercontent.com/61991627/196060703-467ffb65-9abf-4b05-b1df-4daeb431c157.png)

![image](https://user-images.githubusercontent.com/61991627/196238855-3b5d1ca6-6e33-45d4-949f-d5a81c41b50e.png)

ORIGINAL IMAGES
![image](https://user-images.githubusercontent.com/61991627/196239336-1638b6f1-4eea-4f6e-85ba-64522f60bc4d.png)

![image](https://user-images.githubusercontent.com/61991627/196238987-037bc02c-6563-4a5a-ab60-8d07a66e76b3.png)

Can you please suggest some options which i can tweak to obtain good results

**Comment by minakshimathpal** [comment]
@OPHoperHPO As you can see the edged of the extracted artifacts are not smooth, which is the primary focus of my project

**Comment by OPHoperHPO** [comment]
Hello @minakshimathpal, 

You just have to play with the erosion/expansion values of the trimap to get the quality you want. I recommend checking out the `development-tracer` branch, in this version you can easily change these values using cli arguments.


Some examples:

`python3 -m carvekit -i ./workdir/ --device cpu --fp16 False --post fba --trimap_dilation 5 --trimap_erosion 10 --net tracer_b7`
![196238987-037bc02c-6563-4a5a-ab60-8d07a66e76b3_bg_removed](https://user-images.githubusercontent.com/29470622/196373862-bec779c3-94b4-41c6-8766-cedc0919f6c5.png)
![196239336-1638b6f1-4eea-4f6e-85ba-64522f60bc4d_bg_removed](https://user-images.githubusercontent.com/29470622/196373886-e02fcaa1-c13e-419e-bdd3-d6aa10d795d5.png)

**Comment by minakshimathpal** [comment]
@OPHoperHPO thank a lot for quick response
