### ISSUE TITLE
rembg 2.0.29 requires fastapi==0.87.0, but you'll have fastapi 0.78.0 which is incompatible

### ISSUE THREAD

**Issue by theatomus** [OPHoperHPO/image-background-remove-tool#129]
rembg 2.0.29 requires fastapi==0.87.0, but you'll have fastapi 0.78.0 which is incompatible.
rembg 2.0.29 requires numpy==1.23.5, but you'll have numpy 1.22.4 which is incompatible.
rembg 2.0.29 requires pillow==9.3.0, but you'll have pillow 9.0.1 which is incompatible.
rembg 2.0.29 requires uvicorn==0.20.0, but you'll have uvicorn 0.17.6 which is incompatible.

???????????

**Comment by OPHoperHPO** [comment]
We do not support compatibility with rembg, including its dependency versions. Use virtualenv to install rembg or carvekit, or update dependencies to the required versions at your own risk.
