### ISSUE TITLE
how to download the .pth file to local ？

### ISSUE THREAD

**Issue by MathamPollard** [OPHoperHPO/image-background-remove-tool#133]
how to download the .pth file to local? I dont want to download them everytime, it costs a lot of time.

**Comment by MrFox131** [comment]
Hi, @MathamPollard. All models are cached in your local filesystem. They will not be redownloaded till hashes of used models changed in package or you deleted .cache directory in your homedir. In case if you are firmly convinsed that it's not working - notify us and we will reopen and investigate that issue
