### ISSUE TITLE
 Is it possible to re-attach a background image separated from an object? [Question]

### ISSUE THREAD

**Issue by doithun** [OPHoperHPO/image-background-remove-tool#134]
hello. author

I respect the wonderful model you developed.

Currently, when object and background are separated
Only the image of the separated object is saved.

Is there any way to save a separate background image???

If so, is it possible to composite the separated background image back to a specific object???

**Comment by OPHoperHPO** [comment]
You can extract the alpha channel from the background-free image using the function from #130, invert it (255 - alpha_channel numpy array), and then apply it to the original image using the function carvekit.utils.mask_utils.apply_mask. This way, you will obtain only the background image without the object.
