### ISSUE TITLE
Quality differences

### ISSUE THREAD

**Issue by jpg-gamepad** [OPHoperHPO/image-background-remove-tool#146]
Hello,

I am getting different results locally using the CLI than from the demo site [carve.photos/](https://carve.photos/)
What are model and settings are you using on the website?

Thank you!

**Comment by OPHoperHPO** [comment]
Hello @jpg-gamepad,

The reason you are experiencing different results is that the Carve Photos website is powered by our proprietary algorithms that are continuously updated and enhanced for optimal performance. The website utilizes our most recent developments and refined models, which include various optimizations and improvements that are not present in the open-source version of our code available on GitHub.

The GitHub repository provides a solid foundation for background removal, but it is primarily intended for research or as a starting point for further development. On the other hand, our website, carve.photos, benefits from additional code modifications and the integration of the latest models that are specifically optimized to handle a wide range of complex image scenarios more effectively.

Please note that carve.photos is a separate project from the carvekit, and thus it have more advanced features and better quality.

**Comment by CodesHour** [comment]
Can I get a better model for carvekit that provides better result than what it is giving now? If I have to bear a cost, i will be happy to know that.. Thank you.

**Comment by OPHoperHPO** [comment]
Hello @CodesHour 

**For CarveKit, there are no updated models that are not publicly available.**

If you are referring to the models and solutions we use at Carve.Photos: write to us at contact@carve.photos, and we will discuss it.

We also offer a SaaS solution Carve.Photos through our fast and affordable API for background removal, which might suit your needs better if you do not want to pay for extensive GPU server rentals. The solution is highly customizable and can be improved upon request. Moreover, if you need background removal for videos, we have such a solution as well.

> Note: If you wish to purchase a private solution or model for creating competitors to carve.photos, for resale, and other similar cases, it is not possible, as our Terms of Use for private solutions strictly prohibit such use.

**Comment by CodesHour** [comment]
Hello...
Thanks for your reply.

Well, first of all i am not intended to sell your carve.photos code..

All i need it is solely for my own Website, which i am building up.

Now, you have mentioned about API in your last email...

- So, can you share the price per call (presently only for images)?

[Note: My website will also remain free use for all, and may be a small
chage for premium user in future]


-maximum request can be sent per second?


- bulk image upload to remove bgs?


- Maximum image dimensions can be uploaded? I prefer 25 MB atleast.


- Maximum file size? I prefer 20 MB atleast.


-File format support? I prefer jpg, jpeg, png, gif, webp, jfif, heic, heif,
svg.


Presently i can think of these. You may mention any other parameter which
you think i need to know.

**Comment by OPHoperHPO** [comment]
@CodesHour Just a heads up that this repository is specifically for discussions related only to the **CarveKit** project. If you have any questions that don't directly pertain to **CarveKit**, could you kindly send them our way via **email above**? This will keep the repository here focused, organized and related to CarveKit.

**Comment by CodesHour** [comment]
Sorry.. I actually overlooked the email. Now I have sent the same message to that email you have shared. Please reply accordingly.

I also deleted the above comment.
