### ISSUE TITLE
How much in a donation would it take for you to drastically improve this library?

### ISSUE THREAD

**Issue by trafficfox** [OPHoperHPO/image-background-remove-tool#15]
Specially when it comes to regards to product photos with a person in it.

**Comment by OPHoperHPO** [comment]
Hi, @trafficfox. Something around $ 2,000 to buy a new powerful computer.  I need a new powerful computer to train my own neural network model, with which I can significantly improve the quality of the resulting image.  My old laptop is not suitable for such purposes(((  I have considered alternatives such as Google Colab, but it has many limitations, which makes it completely unsuitable for long-term continuous training of a neural network.  Without a new computer, I can only use pre-trained models that were not designed for the purposes of this project, and try to squeeze out everything that is possible using various methods of pre-processing and post-processing of images, which should also improve quality, but not much

**Comment by trafficfox** [comment]
What if I provide you with a powerful computer?
I have one that's accessible from the internet.
12 cores (6 physical) 4GB video RAM.
Is that enough?

**Comment by MarsVard** [comment]
What kind of improvements do you think you can achieve? Is it just the model that needs to be trained using a different dataset? And where would you get that dataset?

**Comment by trafficfox** [comment]
So this is the one with remove.bg (image was upscaled first): https://i.imgur.com/cRR5xxi.jpg
This is the one with yours: https://i.imgur.com/RlXpJbH.png

You see the dark shading around the image, and how her rollerblade was also removed.

Also look on from remove.bg. the hair is nicer too: https://i.imgur.com/J4iLwUQ.jpg

As for dataaset, what would you need? I don't know much about training models.

**Comment by MarsVard** [comment]
@trafficfox you're underestimating the work that remove.bg does, a better dataset won't solve everything

**Comment by trafficfox** [comment]
I think I am. As I said, my field of programming isn't on this so I don't know how much work it actually is.

But I'm willing to pay good money for such a tool though. Because I could seriously make very good use of it.

**Comment by OPHoperHPO** [comment]
@trafficfox 

> What if I provide you with a powerful computer?
> I have one that's accessible from the internet.
> 12 cores (6 physical) 4GB video RAM.
> Is that enough?

Thank you for your help. What graphics card is installed on this computer? How much RAM?

**Comment by trafficfox** [comment]
@OPHoperHPO GTX 1050 ti with 4GB of RAM.

I'd be willing to give you teamviewer + SFTP + SSH access to it.

If this graphics card is not enough, tell me and I can buy a better one.

**Comment by trafficfox** [comment]
Also, 64GB of RAM.

**Comment by OPHoperHPO** [comment]
@MarsVard 

> What kind of improvements do you think you can achieve? Is it just the model that needs to be trained using a different dataset? And where would you get that dataset?


I think that I can achieve results little worse than those that the paid remove.bg service achieved.

First, I need to continue training the u2net neural network model on a much larger dataset with better segmentation. If the results are worse, I will train the model from scratch on images with a resolution of more than 320x320. The author of the neural network trained the current model on this small [dataset](http://saliditydetection.net/duts/), consisting of 10553 images with approximately such segmentation. 
![ILSVRC2012_test_00035585](https://user-images.githubusercontent.com/29470622/85599015-7784ec80-b68f-11ea-9a6b-91c730d81641.jpg)
![ILSVRC2012_test_00035585](https://user-images.githubusercontent.com/29470622/85599031-7a7fdd00-b68f-11ea-90ef-04e845b502f2.png)
Agree, the hair segmentation here is not very high quality.

As a dataset, I plan to try a dataset [COCO](https://cocodataset.org/). Next, I want to continue training the model on my own dataset, which consists of what is not in COCO and other similar datasets. For example, closely photographed hairy objects in high resolution, screenshots, etc. I plan to collect my own data set from free images on the Internet and my own collections of photographs. Segmenting my dataset is not a problem.

In addition to the model trained on the good data set, I need to look for methods to improve the boundaries of the processed image, because the current result is not bad, but i need better. Perhaps a second neural network will help here, aimed solely at improving borders. I already have a dataset for her. I also want to try some methods to improve boundaries using libraries such as cv2, skimage and others.

In addition to this, I have an idea to train the classifier of objects to a huge number of different objects, so that then each object in the photo is sent to remove the background of the neural network model specially trained for this type of object.

**Comment by OPHoperHPO** [comment]
> So this is the one with remove.bg (image was upscaled first): https://i.imgur.com/cRR5xxi.jpg
> This is the one with yours: https://i.imgur.com/RlXpJbH.png
> 
> You see the dark shading around the image, and how her rollerblade was also removed.
> 
> Also look on from remove.bg. the hair is nicer too: https://i.imgur.com/J4iLwUQ.jpg
> 
> As for dataaset, what would you need? I don't know much about training models.

@trafficfox 
It looks like you used the **old** version of the program to remove the background from this photo. Update the program and
try removing the background again, the result should be much better. Also try using different image preprocessing and post-processing algorithms.

[Test it on google colab](https://colab.research.google.com/gist/OPHoperHPO/1231a641476fcb56ca1ca199e849d9a2/image-background-remove-tool.ipynb)
![image](https://user-images.githubusercontent.com/29470622/85603035-51f9e200-b693-11ea-8d60-019f7a55adf5.png)

### So here are some more results.
* Image 1:
Original image:
![1](https://user-images.githubusercontent.com/29470622/85606758-d26e1200-b696-11ea-99dd-0ee7df516cae.png)
My result:
![3](https://user-images.githubusercontent.com/29470622/85606808-def26a80-b696-11ea-8df9-c50f8d975a08.png)
My result + white background:
![2](https://user-images.githubusercontent.com/29470622/85606836-e44fb500-b696-11ea-8f48-9b6755ebabf7.png)
remove.bg result:
![1-removebg-preview](https://user-images.githubusercontent.com/29470622/85606887-ef0a4a00-b696-11ea-9025-c20a7824fa1d.png)

* Image 2:
Original image:
![Original image](https://user-images.githubusercontent.com/29470622/85604617-cc773180-b694-11ea-9750-99c472d9e07d.png)
My result:
![My result](https://user-images.githubusercontent.com/29470622/85604694-e0bb2e80-b694-11ea-9eac-88eeb8e47773.png)
My result + white background:
![My result + white background](https://user-images.githubusercontent.com/29470622/85604782-f29cd180-b694-11ea-9c46-bfeb5973a3c4.png)
Remove.bg result:
![remove.bg result](https://user-images.githubusercontent.com/29470622/85604881-06e0ce80-b695-11ea-9b8e-e6cd8f4937ca.png)

**Comment by trafficfox** [comment]
@OPHoperHPO On the image I sent of the girl, you see it still cuts a bit.
It sounds like quite a bit of work though, but I _seriously_ need a tool like this.

If I provide you with a computer, and pay you for your time, would you be willing to go through with this?
I don't mind it remaining open source either.

**Comment by OPHoperHPO** [comment]
> @OPHoperHPO GTX 1050 ti with 4GB of RAM.
> 
> I'd be willing to give you teamviewer + SFTP + SSH access to it.
> 
> If this graphics card is not enough, tell me and I can buy a better one.
> Also, 64GB of RAM.
> What if I provide you with a powerful computer?
> I have one that's accessible from the internet.
> 12 cores (6 physical) 4GB video RAM.
> Is that enough?

@trafficfox
Such a computer, in theory, should be suitable for training neural networks


> @OPHoperHPO On the image I sent of the girl, you see it still cuts a bit.
> It sounds like quite a bit of work though, but I _seriously_ need a tool like this.
> 
> If I provide you with a computer, and pay you for your time, would you be willing to go through with this?
> I don't mind it remaining open source either.

This project is a **nonprofit open source project**. Therefore, unfortunately, I can not provide you with any personal services for the development or modernization of this project for any fee.
But you can give me access to this computer as a donation of computing resources. You can also give me financial support and speed up the project development process by donating some funds.

**Comment by trafficfox** [comment]
Thats what I mean, not paying you to work for me, but donating so that you have the time for it.
Yupp, I can give access to it.
Email me at patrick@trafficfox.no and lets take it from there in regards to giving you access and such.

**Comment by OPHoperHPO** [comment]
@trafficfox 
Okay, wait for the letter from this address `farv ard34 @gm ail.com` (without spaces).

**Comment by MarsVard** [comment]
@trafficfox do you think you can achieve this for mobile?

**Comment by trafficfox** [comment]
@MarsVard what exactly do you mean?

**Comment by MarsVard** [comment]
The results achieved by Remove.bg

**Comment by trafficfox** [comment]
@MarsVard Sorry but I'm still not sure of what you mean.
To achieve this on a mobile application using their API? Or responsive website?
Or achieve the same results on a mobile device internally?

**Comment by MarsVard** [comment]
Oh Sorry, I mean achieve the same results on a mobile device internally, yes.

**Comment by trafficfox** [comment]
I honestly doubt it, tbh.
Using this library, it takes a couple of seconds on a mid-end GPU. Mobile device GPUs are far weaker than this.

Not saying it's impossible, but there are much bigger hurdles to doing it on a mobile device than on a desktop.
The best is building it as an API

**Comment by MarsVard** [comment]
Prisma does a pretty good job at it + the model is only 10mb...
They do have the time + money to train the shit out of it :D but still

**Comment by atugar** [comment]
Try https://vast.ai/. You can rent monster computers for training with multiple GPU's and 100+ GB system RAM for less than $1/hour. 
I am not affiliated with them. Just use it for my training.
