### ISSUE TITLE
Take a look at detectron2 when working with mask r-cnn + PointRend

### ISSUE THREAD

**Issue by yncki** [OPHoperHPO/image-background-remove-tool#16]
https://github.com/facebookresearch/detectron2/tree/master/projects/PointRend

![image](https://user-images.githubusercontent.com/1530496/85185314-c992d000-b293-11ea-9dd6-937b4e004751.png)

**Comment by OPHoperHPO** [comment]
At first glance, this bunch of neural networks gives an amazing result. I’ll try it in the coming days. Thanks for the info.

**Comment by OPHoperHPO** [comment]
Closed due to outdated.
