### ISSUE TITLE
Error in Google Cloud Run

### ISSUE THREAD

**Issue by massonetto** [OPHoperHPO/image-background-remove-tool#18]
Hello,

I am try run your tool in a container, in Google Cloud Run. This container have a **2 gb** limit of memory. In my tests, the aplication exced this value and crash.

![Captura de tela de 2020-06-22 20-42-40](https://user-images.githubusercontent.com/10254699/85345507-03005100-b4c9-11ea-8bef-a360048382cc.png)

Is there some modify/solution to down memory usage?

Thanks

**Comment by OPHoperHPO** [comment]
Hello, @massonetto.

The program with standard settings (bbd-fastrcnn / u2net / rtb-bnb) in the peak consumes ~ 2.5, Gb, so for normal operation of the program with these settings you need a minimum amount of RAM 3 Gb, but you can always change its settings to reduce consumption. Try turning off image preprocessing methods by specifying the `-prep None` argument. A program without preprocessing methods (None / u2net / rtb-bnb2) consumes a maximum of ~ 1.4 Gb of RAM.

**Comment by massonetto** [comment]
Thanks @OPHoperHPO 

I will try this and notify you

**Comment by massonetto** [comment]
**It's works** :smile: 

I also made a modification to resize the photo before the process, it gained more memory.

![Captura de tela de 2020-06-23 10-50-43](https://user-images.githubusercontent.com/10254699/85411985-72b12300-b53f-11ea-8019-3701059b79f7.png)

Thanks

**Comment by OPHoperHPO** [comment]
It's fine!

> **It's works**
