### ISSUE TITLE
Error : terminate called after throwing an instance of 'dmlc::Error'

### ISSUE THREAD

**Issue by ctricot** [OPHoperHPO/image-background-remove-tool#19]
Hello

I have an exception that I can't explain when I try to process these photo :
[4db0c65b27ec01de3edc68046707cd53](https://user-images.githubusercontent.com/6390647/85416048-52e52380-b56e-11ea-8cfe-06f605f44ddc.png)

The code 

`
model_name="u2net"
model = model_detect(model_name)  # Load model
preprocessing_method = preprocessing.method_detect(preprocessing_method_name)
postprocessing_method = postprocessing.method_detect(postprocessing_method_name)
preprocessing_method_name="bbd-fastrcnn"
postprocessing_method_name="rtb-bnb"
image = model.process_image(input_path, preprocessing_method, postprocessing_method) 
`

The error trace :
```
terminate called after throwing an instance of 'dmlc::Error'
  what():  [16:23:54] src/operator/image/./image_random-inl.h:251: Check failed: nchannels == 3 || nchannels == 1: The first dimension of input tensor must be the channel dimension with either 1 or 3 elements, but got input with shape [4,1000,461]
Stack trace:
  [bt] (0) /home/metanewlife/.local/lib/python3.8/site-packages/mxnet/libmxnet.so(+0x307d3b) [0x7f7c21cb4d3b]
  [bt] (1) /home/metanewlife/.local/lib/python3.8/site-packages/mxnet/libmxnet.so(+0x89e5f3) [0x7f7c2224b5f3]
  [bt] (2) /home/metanewlife/.local/lib/python3.8/site-packages/mxnet/libmxnet.so(mxnet::imperative::SetShapeType(mxnet::Context const&, nnvm::NodeAttrs const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, mxnet::DispatchMode*)+0x1d27) [0x7f7c24e4eaa7]


Aborted
```

**Comment by OPHoperHPO** [comment]
Hello, @ctricot. This error is related to the file extension. This flaw has just been fixed.
