### ISSUE TITLE
colab demo not working

### ISSUE THREAD

**Issue by madrainbo** [OPHoperHPO/image-background-remove-tool#20]
tried to run the colab... with no success

**Comment by OPHoperHPO** [comment]
Hello,@madrainbo.  Can you provide the logs of the cell where you got an error?  I just checked the demo and it works.

**Comment by madrainbo** [comment]
Good that you asked for logs.. seems like the connection reset of the notebook caused it.
Able to test now. Good work.
Works perfectly with just an object and plane background. 
However, when I gave it the attached image, result was weird. Sharing it just for you to be able to test the same.
![20200513_175403](https://user-images.githubusercontent.com/49408053/85509608-ec1a4580-b613-11ea-8ceb-d7c1753ecc92.jpg)
