### ISSUE TITLE
[ALPHA][Version 3.3] Bugs

### ISSUE THREAD

**Issue by OPHoperHPO** [OPHoperHPO/image-background-remove-tool#24]
## Leave a comment about any errors that you found in this [version](https://github.com/OPHoperHPO/image-background-remove-tool/pull/22).

**Comment by pubkey** [comment]
Hi, thank you for fixing the memory leak. I tried this out and have another problem.
The API now does not finish requests. So when I do the example curl request, the image gets processed but the curl request itself never finishes and it does not download the image.

I started the server with these params:
`python3 http_api.py -auth false -port 5000 -host 0.0.0.0 -m u2net -prep None -postp fba`

**Comment by marielen** [comment]
Hi!

I am running the code for 12 similar images from jpeg format. The code is running for some of them, but for the other ones I am getting the error below.

Do you know what could be happening?

```cli
(venv) ➜  image-background-remove-tool git:(master) ✗ python3 main.py -i input -o output -m u2net -prep bbd-fastrcnn -postp rtb-bnb
Remove Background:  25%|############                                    | 3/12 [02:51<08:38, 57.64s/image]Traceback (most recent call last):
  File "main.py", line 152, in <module>
    cli()
  File "main.py", line 148, in cli
    process(input_path, output_path, model_name, preprocessing_method_name, postprocessing_method_name)
  File "main.py", line 113, in process
    image = model.process_image(file_path, preprocessing_method, postprocessing_method)
  File "/Users/marielen/Documents/Projects/image-background-remove-tool/libs/networks.py", line 94, in process_image
    image, org_image = self.__load_image__(data)  # Load image
  File "/Users/marielen/Documents/Projects/image-background-remove-tool/libs/networks.py", line 144, in __load_image__
    image = io.imread(data)  # Load image if there is a path
  File "/Users/marielen/Documents/Projects/image-background-remove-tool/venv/lib/python3.7/site-packages/skimage/io/_io.py", line 61, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/Users/marielen/Documents/Projects/image-background-remove-tool/venv/lib/python3.7/site-packages/skimage/io/manage_plugins.py", line 210, in call_plugin
    return func(*args, **kwargs)
  File "/Users/marielen/Documents/Projects/image-background-remove-tool/venv/lib/python3.7/site-packages/imageio/core/functions.py", line 265, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/Users/marielen/Documents/Projects/image-background-remove-tool/venv/lib/python3.7/site-packages/imageio/core/functions.py", line 182, in get_reader
    "Could not find a format to read the specified file in %s mode" % modename
ValueError: Could not find a format to read the specified file in single-image mode
Remove Background:  25%|############                                    | 3/12 [02:51<08:35, 57.33s/image]
```

**Comment by OPHoperHPO** [comment]
> Hi!
> 
> I am running the code for 12 similar images from jpeg format. The code is running for some of them, but for the other ones I am getting the error below.
> 
> Do you know what could be happening?
> 
> ```cli
> (venv) ➜  image-background-remove-tool git:(master) ✗ python3 main.py -i input -o output -m u2net -prep bbd-fastrcnn -postp rtb-bnb
> Remove Background:  25%|############                                    | 3/12 [02:51<08:38, 57.64s/image]Traceback (most recent call last):
>   File "main.py", line 152, in <module>
>     cli()
>   File "main.py", line 148, in cli
>     process(input_path, output_path, model_name, preprocessing_method_name, postprocessing_method_name)
>   File "main.py", line 113, in process
>     image = model.process_image(file_path, preprocessing_method, postprocessing_method)
>   File "/Users/marielen/Documents/Projects/image-background-remove-tool/libs/networks.py", line 94, in process_image
>     image, org_image = self.__load_image__(data)  # Load image
>   File "/Users/marielen/Documents/Projects/image-background-remove-tool/libs/networks.py", line 144, in __load_image__
>     image = io.imread(data)  # Load image if there is a path
>   File "/Users/marielen/Documents/Projects/image-background-remove-tool/venv/lib/python3.7/site-packages/skimage/io/_io.py", line 61, in imread
>     img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
>   File "/Users/marielen/Documents/Projects/image-background-remove-tool/venv/lib/python3.7/site-packages/skimage/io/manage_plugins.py", line 210, in call_plugin
>     return func(*args, **kwargs)
>   File "/Users/marielen/Documents/Projects/image-background-remove-tool/venv/lib/python3.7/site-packages/imageio/core/functions.py", line 265, in imread
>     reader = read(uri, format, "i", **kwargs)
>   File "/Users/marielen/Documents/Projects/image-background-remove-tool/venv/lib/python3.7/site-packages/imageio/core/functions.py", line 182, in get_reader
>     "Could not find a format to read the specified file in %s mode" % modename
> ValueError: Could not find a format to read the specified file in single-image mode
> Remove Background:  25%|############                                    | 3/12 [02:51<08:35, 57.33s/image]
> ```

Hi, @marielen. Can you send to me the list of filenames of input files?
