### ISSUE TITLE
HTTP-API Memory leak

### ISSUE THREAD

**Issue by pubkey** [OPHoperHPO/image-background-remove-tool#27]
I found a memory leak in the http-api. Each request fills up the RAM a little bit more, until is crashes.
I tried several combinations of post- and pre-processors but all create the same problem.

Reproduce:

1. Start http-api with network `u2net` and disable all pre/post-processors.
`python3 http_api.py -auth false -port 5000 -host 0.0.0.0 -m u2netp -postp No -prep None`
2. Make several requests against the API, the more requests you do, the more the memory is filled up. I can do about 30 requests and then my pc will crash.

```bash
curl -H 'X-API-Key: test'                                   \
       -F 'image_file=@./test.jpg'                 \
       -F 'size=auto'                                       \
       -f http://localhost:5000/api/removebg -o no-bg.png
```

EDIT:
I hacked the main.py to also do many image processings, there the memory leak does not occur. So this is likely sth with the http-server.

**Comment by OPHoperHPO** [comment]
Fixed. Check out the nontested branch.
