### ISSUE TITLE
Retrain model with custom datasets

### ISSUE THREAD

**Issue by vhghorecha** [OPHoperHPO/image-background-remove-tool#3]
You really did a great job.
I just wanted to know how can we retrain the existing model with custom datasets??

**Comment by OPHoperHPO** [comment]
This program is based on the Deeplab model, so to train a neural network with a different dataset, it will be enough to train it according to the official instructions for the model and replace the model loading paths in my main.py script.

[Link to the official model repository.](https://github.com/tensorflow/models/tree/master/research/deeplab)
