### ISSUE TITLE
Using pre-trained model but want to train it further

### ISSUE THREAD

**Issue by haseebehsan** [OPHoperHPO/image-background-remove-tool#30]
Hi, I'm pretty new to this but its clear that this repo has been using pre-trained models, but I want to know the origin of these pre-trained models because what I want is the training code or training pipe-line because I want to train these models further on the images data that we would create on our end.
Can anyone help me figure it out?

**Comment by OPHoperHPO** [comment]
Hello, @haseebehsan. 


The pretrained models used in this tool are the pretrained models provided by the neural network authors from original neural network github repo.


So, you can find code for training neural networks in  their original github repos. For example, u2net training code can be found [here](https://github.com/NathanUA/U-2-Net). Links for other networks look in the README.md or CREDITS.md or just google.
