### ISSUE TITLE
Tried Running it in Colab, but getting errors

### ISSUE THREAD

**Issue by lawrenceong001** [OPHoperHPO/image-background-remove-tool#38]
Hello -- I tried running it in colab against my own image, but it's coming back with errors:

`python3: can't open file 'main.py': [Errno 2] No such file or directory`
``
`---------------------------------------------------------------------------`
``
`FileNotFoundError                         Traceback (most recent call last)`
``
`<ipython-input-5-b3dfc451a535> in <module>()`
`     16   f = "1.jpg"`
`     17   get_ipython().system('python main.py -i ./1.jpg -o ./2.png -m $model_name -prep $preprocessing -postp $postprocessing')`
`---> 18   image = Image.open("./2.png")`
`     19   new = Image.new("RGB", image.size, (255, 255, 255))`
`     20   new.paste(image, (0,0), image)`
``
`/usr/local/lib/python3.6/dist-packages/PIL/Image.py in open(fp, mode)`
`   2807 `
`   2808     if filename:`
`-> 2809         fp = builtins.open(filename, "rb")`
`   2810         exclusive_fp = True`
`   2811 `
``
`FileNotFoundError: [Errno 2] No such file or directory: './2.png'`
``

Am I missing something here? tks.

**Comment by OPHoperHPO** [comment]
Hello. Try resetting colab runtime and starting all cells again.
