### ISSUE TITLE
Keeping the shadows of Objects

### ISSUE THREAD

**Issue by muhammadabdullah34907** [OPHoperHPO/image-background-remove-tool#41]
@OPHoperHPO 

I am working on only 2 classes i.e CARS and TRUCKS images. The current model of U2NET does remove background properly but I further improved it by retraining it using carvana dataset from kaggle.

BUT

The challenge that I have currently is that I don't want to lose shadows of cars. I want to keep the shadows as foreground mask for every car and truck.

What solution do you propose to keep the shadows ?

Either I should have masks with shadows for training ? and then retraining it ?
Either I should apply some post-processing methods(if you have suggestion) to get the shadows as well ?
ANY PROPOSED SOLUTION WOULD BE APPRECIATED

Currently When I pass the image for example below, it remove the shadows which i don't want to lose

![99254190-c6484400-2833-11eb-8d7d-81cc55b4c693](https://user-images.githubusercontent.com/55294154/99341731-414d4100-28ac-11eb-971c-f27060eb78d0.jpg)

**Comment by OPHoperHPO** [comment]
Hello @muhammadabdullah34907,

I see several ways to solve this problem:
* For good shadow preservation, you need to train the model for segmentation on car masks where shadows are present.
* You can skip training this model and try to get by with post-processing algorithms - image matting and shadow detection algorithms. I wrote colab notebook as an example of such an algorithm. Its results can be improved by adapting this combination of algorithms and use a better shadow detection algorithm than I used. I used the algorithm that was easiest to integrate into notebook. 
* Create a computer simulation of the shadow near the bottom of the car, as remove.bg does.

Files:
* [Colab Notebook](https://colab.research.google.com/gist/OPHoperHPO/86438f6b794f1950bbbea9da23ba0cc6/cars-shadow-detection.ipynb)

Here is some examples:
1) Original image: 
![7](https://user-images.githubusercontent.com/29470622/99675364-db86d200-2ac2-11eb-948c-5fd1fe9f51b0.jpeg)
Colab notebook:
![7](https://user-images.githubusercontent.com/29470622/99675381-e17cb300-2ac2-11eb-861d-c6bef0ee0f74.png)
Remove.bg:
![7](https://user-images.githubusercontent.com/29470622/99675478-fc4f2780-2ac2-11eb-8958-009e1e71f115.png)


2) Original image: 
![9](https://user-images.githubusercontent.com/55294154/99341731-414d4100-28ac-11eb-971c-f27060eb78d0.jpg)
Colab notebook:
![6](https://user-images.githubusercontent.com/29470622/99674858-4d125080-2ac2-11eb-891e-4bf73e82434f.png)
Remove.bg:
![r](https://user-images.githubusercontent.com/29470622/99675014-729f5a00-2ac2-11eb-80c1-054b53118e40.png)


3) Original image: 
![1](https://user-images.githubusercontent.com/29470622/99675059-7b902b80-2ac2-11eb-92f2-e71a07570a45.jpeg)
Colab notebook:
![1](https://user-images.githubusercontent.com/29470622/99675084-81860c80-2ac2-11eb-8520-5e8f35e2dfa8.png)
Remove.bg:
![r](https://user-images.githubusercontent.com/29470622/99675144-96fb3680-2ac2-11eb-9265-6c9b9d02f2ee.png)

4) Original image: 
![9](https://user-images.githubusercontent.com/29470622/99674393-b6459400-2ac1-11eb-81b0-43c80896604a.jpeg)
Colab notebook:
![9_m](https://user-images.githubusercontent.com/29470622/99674552-ee4cd700-2ac1-11eb-83be-db2373b7cff8.png)
Remove.bg:
![9](https://user-images.githubusercontent.com/29470622/99674597-01f83d80-2ac2-11eb-9815-ab85cf6d77d1.png)

**Comment by muhammadabdullah34907** [comment]
@OPHoperHPO 
Thank you so much for the detailed response. Remove.bg created fake shadows which is not the target of what i am going to achieve but the example that you have share by writing post-processing method yourself is the one I am interested. Do you suggest me to change the detection method and it will eventually start getting the shadows, that's what you are referring ?

**Comment by OPHoperHPO** [comment]
> @OPHoperHPO 
> Thank you so much for the detailed response. Remove.bg created fake shadows which is not the target of what i am going to achieve but the example that you have share by writing post-processing method yourself is the one I am interested. Do you suggest me to change the detection method and it will eventually start getting the shadows, that's what you are referring ?

Yes

**Comment by muhammadabdullah34907** [comment]
@OPHoperHPO real shadows are not working properly, So i was search for fake shadows like remove.bg does. Will you please suggest something that works well ?

**Comment by georgeemr** [comment]
Did you manage to resolve this?

**Comment by varunmittal50** [comment]
@muhammadabdullah34907 I am also looking to improve the model to generate accurate masks for cars, can you please help on the custom training process or share your custom trained model for cars

**Comment by OPHoperHPO** [comment]
Closed as it will be improved in the future
