### ISSUE TITLE
multiple images

### ISSUE THREAD

**Issue by yumihconnie** [OPHoperHPO/image-background-remove-tool#42]
hello, is it possible to use this to remove backgrounds for multiple images at a time from a folder in google drive instead of using an image url and inserting them one at a time? I'm using google colab to run this. Thank you

**Comment by OPHoperHPO** [comment]
Hello @yumihconnie,
Yes it is possible. Just mount your google drive to the colab container and run the program using the console command. You can read more about all the options of the program's console interface in the README of this repository.
Place this code in a new cell colab and specify the paths to your folders in google drive.
`!python main.py -i path_to_folder_in_gdrive -o path_to_output_folder_in_gdrive -m u2net -prep None -postp No`

**Comment by yumihconnie** [comment]
Hello,
Sorry, but I'm new to coding. Could you please take a look at my screen shot? Did I write the i and o correctly? 
!python main.py -i path_to_folder_in_gdrive -o path_to_output_folder_in_gdrive -m u2net -prep None -postp No

also not sure about how to put in the rest of it. 
Thank you.


![Untitled](https://user-images.githubusercontent.com/71809121/99737393-30f8ba00-2a96-11eb-8019-e0fde4de6c2b.png)

**Comment by yumihconnie** [comment]
![Untitled](https://user-images.githubusercontent.com/71809121/99737940-63ef7d80-2a97-11eb-8c4d-92a4a2a4e4d2.png)

**Comment by OPHoperHPO** [comment]
@yumihconnie, 

It should be like this:
```
path_to_folder_in_gdrive = "/content/drive/MyDrive/" #@param {type:"string"}
path_to_output_folder_in_gdrive = "./" #@param {type:"string"}
model_name = "u2net" #@param {type:"string"}
prep = "No" #@param {type:"string"}
postp = "None" #@param {type:"string"}
!python main.py -i $path_to_folder_in_gdrive -o $path_to_output_folder_in_gdrive -m $model_name -prep $prep -postp $postp
```

![image](https://user-images.githubusercontent.com/29470622/99751908-f1ca7780-2b2e-11eb-9e5a-688044f28046.png)

**Comment by yumihconnie** [comment]
thank you for your help.  I still must be doing something wrong. I think in connection to my gdrive? Could you please see attached?

https://colab.research.google.com/drive/1lVId0r4wGXPsZZk4zl67iX9KBejV_Bnz?usp=sharing

![error](https://user-images.githubusercontent.com/71809121/99754574-a2e0fb80-2ab6-11eb-9eed-b5832cc878ce.png)

**Comment by OPHoperHPO** [comment]
@yumihconnie,
1) You need to add \ character  to any spaces in path. It should be like: /content/drive/My\ Drive...
2) Fix your output path to /content/drive/My\ Drive/hanbok/hanpreprocessed

**Comment by yumihconnie** [comment]
thank you! also needed to add '/' at the end. It seems like it's running now, I can see it going through my images. Ran it a few times with different settings but it doesn't output anything into my folder and I have no recent files in my google drive.
