### ISSUE TITLE
GPU Not Used

### ISSUE THREAD

**Issue by adel6666** [OPHoperHPO/image-background-remove-tool#48]
Hello, thank you for this good job, I tested the code but I cannot run it on GPUs, as I would like to run the solution on videos I would like to know if there is a way to run it on gpu because now it takes about 40 minutes / video. Thank you :)

**Comment by supachai1998** [comment]
me too... 26.99s/images but have 2000 per category. now I have 11 category

**Comment by nadermx** [comment]
@supachai1998 so you are saying that you got it working with the GPU by installing what requirements?

**Comment by drmanhatin** [comment]
Same issue here, rtx 3080, no gpu usage

**Comment by OPHoperHPO** [comment]
Fixed
