### ISSUE TITLE
Is there a way to save each image with a white background? [question]

### ISSUE THREAD

**Issue by gelazari** [OPHoperHPO/image-background-remove-tool#60]
Hi all, is there a way to save each image with a white background?  I believe I could insert somewhere before saving the image the required lines to perform the aforementioned action. Thanks in advance for your time and consideration.

**Comment by beppefolder** [comment]
hi! Did you find a working solution?
Thank you

**Comment by glazaridis** [comment]
nope

**Comment by beppefolder** [comment]
I solved returning the mask directly from interface.py and manipulating the original image!
Then you can manage the background as you want.
Hope this help!

**Comment by glazaridis** [comment]
Make a PR or a change in a branch
