### ISSUE TITLE
Issue and possible future deterrents

### ISSUE THREAD

**Issue by cramik** [OPHoperHPO/image-background-remove-tool#62]
At the moment I'm getting this issue with my dataset of dogs that I'm removing the backgrounds from
`(base) cramik@DESKTOP-G88PL8G:/mnt/c/dog/image-background-remove-tool$ python3 main.py -i /mnt/c/dogwitbg -o /mnt/c/dogwitoutbg -m u2net -prep bbd-fastrcnn -postp rtb-bnb
Remove Background:  23%|############1                                         | 452/2001 [2:11:51<6:52:10, 15.97s/image]Traceback (most recent call last):
  File "main.py", line 152, in <module>
    cli()
  File "main.py", line 148, in cli
    process(input_path, output_path, model_name, preprocessing_method_name, postprocessing_method_name)
  File "main.py", line 113, in process
    image = model.process_image(file_path, preprocessing_method, postprocessing_method)
  File "/mnt/c/dog/image-background-remove-tool/libs/networks.py", line 94, in process_image
    image, org_image = self.__load_image__(data)  # Load image
  File "/mnt/c/dog/image-background-remove-tool/libs/networks.py", line 153, in __load_image__
    image = self.__ndrarray2tensor__(image)  # Convert image from numpy arr to tensor
  File "/mnt/c/dog/image-background-remove-tool/libs/networks.py", line 164, in __ndrarray2tensor__
    if image.shape[2] == 1:
IndexError: tuple index out of range`

I'm not sure what this is caused by but to prevent it or even troubleshoot it, I think it could be useful to either have an option to show the file name that is being accessed or even add an argument to delete files that have been processed or add them to a database so the user can restart the process without losing progress.

**Comment by cramik** [comment]
at least one of the issues was that it was treating folders as files btw, I'm still running the dataset though so I'll have to see if another one comes up

**Comment by OPHoperHPO** [comment]
Filename display.
Currently not feasible. In the current version, image processing is carried out in batches, so the appeal goes directly to several photos at the same time. In view of which, in the case of a large array of images, progress display will break due to the large amount of information displayed in the terminal.

Issues with folders.
Fixed in the latest release.
