### ISSUE TITLE
Any pre-trained model For shoewear or fashion ? 

### ISSUE THREAD

**Issue by firaki12345-cmd** [OPHoperHPO/image-background-remove-tool#64]
Hi thank you so much for making this script.

but i want to remove background of shoe images, i do get good results from the given trained models.

are there any fashion pre-trained models i can use with this Script ? 

Thanks )

**Comment by firaki12345-cmd** [comment]
bump. Please help

**Comment by OPHoperHPO** [comment]
No, there is no pre-trained model for this, perhaps one will be added in the future.
