### ISSUE TITLE
Google Colab / Kaggle Does not use GPU At ALL 

### ISSUE THREAD

**Issue by firaki12345-cmd** [OPHoperHPO/image-background-remove-tool#65]
HI, i am using the "U2NET" model with default pre-processing and proceesing values.

but it takes approx 34 mins for 100 images using Both GPU And CPU or None as well (What am i doing wrong) 

I tried reading images both from Google drive as well as files loaded into kaggle or google colab itself. (Still takes Same Time)

**Proof that only CPU gets USED:**

https://i.postimg.cc/2SVzXNRh/Kaggle.png

Please, Help Thanks

**Comment by OPHoperHPO** [comment]
Hello, this problem has been completely fixed in the new release version.
