### ISSUE TITLE
Can't find libs fils and used packages 

### ISSUE THREAD

**Issue by AimadGUALLAL** [OPHoperHPO/image-background-remove-tool#72]
I want to test the solution in your notebook used for shadow detection but can't find libs and packages used networks , transformers ....

**Comment by OPHoperHPO** [comment]
This feature is planned to be implemented in the far future in the main code of the repository, not in the demo code attached to the issue, so it will be fixed and added later. At the moment, the notebook from #40 only works in release 3.2.1. If you want to check it out, checkout to version 3.2.1 

We are always happy to for any contributions to this repository.
