### ISSUE TITLE
can share the model?

### ISSUE THREAD

**Issue by mmxuan18** [OPHoperHPO/image-background-remove-tool#85]
is this project can run local ?

**Comment by OPHoperHPO** [comment]
Hi, @mmxuan18 

This open-source project **does not** depend on third-party background removal services in any way. 
It works **offline** and **runs entirely locally on your computer.** 
Download links for all models are public and contained within the auto model installer code. 
You can find them on this [link](https://github.com/OPHoperHPO/image-background-remove-tool/blob/f0a68a19488ba6d1ade1b5cd32e87fa6f8e946e4/carvekit/utils/download_models.py#L14).
